# Generated by Django 3.0.6 on 2020-10-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('phoneno', models.IntegerField()),
            ],
        ),
    ]
